### ISSUE TITLE
NLMIXR crashing 

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#230]
Hello, I am running a very simple code of an exponential model fitting some growth data. While the code runs and the models are fitted, it reaches the covariance stage which completes at 100% and then R crashes. I am providing the code please let me know how and I can provide the data as well.

```R
> rm(list` = ls())
> .libPaths(.libPaths()[regexpr("nlmixr",.libPaths())!=-1])
> libraries <- c("openxlsx", "ggplot2")
> library(nlmixr)
> 
> lapply(libraries, require, character.only = TRUE)
> 
> expon <- function() {
>   ini({
>     tV0 <- -3
>     tkgrow <- -3
>     prop.err <- 0.3
>     
>     eta.V0 ~ 1
>     eta.kgrow ~ 1
>     
>   })
>   model({
>     V0 <- exp(tV0+eta.V0)
>     KGROW <- exp(tkgrow + eta.kgrow)
>     V(0) =V0;
>     
>     d/dt(V) = KGROW * V
>     V~prop(prop.err)
>   })
> }
> 
> dat <- read.xlsx("./Data/example.xlsx)
> 
> fitexpon <- nlmixr(expon, dat, `'focei')
> 
```

**Comment by mattfidler** [comment]
You can attach data to the issue by zipping the excel file and then attaching the data

**Comment by DimitrisVoul** [comment]
[example.zip](https://github.com/nlmixrdevelopment/nlmixr/files/3600488/example.zip)

**Comment by mattfidler** [comment]
```sh
0x00007ffff7962e0b in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7962e0b in raise () from /lib64/libc.so.6
#1  0x00007ffff794c535 in abort () from /lib64/libc.so.6
#2  0x00007ffff79a87e7 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff79b0628 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff79b21fc in _int_free () from /lib64/libc.so.6
#5  0x00007fffee73f94a in rxOptionsFree () at par_solve.c:1478
#6  0x00007fffee772127 in rxSolveFree () at rxData.cpp:2385
...
double free or corruption (!prev)
```

**Comment by DimitrisVoul** [comment]
I am sorry I not sure what that means. Is there some corruption in the data file?

**Comment by mattfidler** [comment]
No.  Sorry that is my own internal notes for the backtrace.  The bug is actually in RxODE.

**Comment by mattfidler** [comment]
If you update nlmixr and RxODE to the github versions the example should work

``` r
## devtools::install_github("nlmixrdevelopment/RxODE")
## devtools::install_github("nlmixrdevelopment/nlmixr")
library(nlmixr)

download.file("https://github.com/nlmixrdevelopment/nlmixr/files/3600488/example.zip", "example.zip")
unzip("example.zip")

libraries <- c("openxlsx", "ggplot2", "nlmixr")

tmp <- lapply(libraries, require, character.only = TRUE)
#> Loading required package: openxlsx
#> Loading required package: ggplot2

expon <- function() {
  ini({
    tV0 <- -3
    tkgrow <- -3
    prop.err <- 0.3

    eta.V0 ~ 1
    eta.kgrow ~ 1

  })
  model({
    V0 <- exp(tV0+eta.V0)
    KGROW <- exp(tkgrow + eta.kgrow)
    V(0) =V0;

    d/dt(V) = KGROW * V
    V~prop(prop.err)
  })
}

dat <- read.xlsx("example.xlsx")

fitexpon <- nlmixr(expon, dat, 'focei', control=list(print=0))
#> Calculate ETA-based prediction and error derivatives:
#> Using sympy via reticulate
#> Calculate Jacobian
#> [====|====|====|====|====|====|====|====|====|====
#> Calculate Sensitivities
#> [====|====|====|====|====|====|==
#> Load into sympy...
#> done
#> Calculate ∂(f)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====
#> Calculate ∂(R²)/∂(η)
#> [====|====|====|====|====|====|====|====|====|====
#> Freeing Python/SymPy memory...
#> done
#> ################################################################################
#> Optimizing expressions in Predictions/EBE model...done
#> Compiling Predictions/EBE model...done
#> Optimizing expressions in Inner model...done
#> Compiling Inner model...done
#> The model-based sensitivities have been calculated.
#> Calculating covariance matrix
#> [====|====|====|====|====|====|====|====|====|====done
#> Calculating residuals/tables
#> done.
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Initial ETAs were nudged; (Can control by
#> foceiControl(etaNudge=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : ETAs were reset to zero during optimization; (Can
#> control by foceiControl(resetEtaP=.))
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Using S matrix to calculate covariance, can check
#> sandwich or R matrix with $covRS and $covR
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Gradient problems with initial estimate and covariance;
#> see $scaleInfo
#> Warning in (function (uif, data, est = NULL, control = list(), ...,
#> sum.prod = FALSE, : Some variances were zero, replaced with 1.

print(fitexpon)
#> ── nlmixr FOCEi (outer: nlminb) fit ─────────────────────────────────────── 
#>            OBJF       AIC       BIC Log-likelihood Condition Number
#> FOCEi -8496.332 -3891.639 -3862.519        1950.82         6.355944
#> 
#> ── Time (sec; $time): ───────────────────────────────────────────────────── 
#>            setup optimize covariance table    other
#> elapsed 5.903327 0.898236   0.898239 0.118 6.353198
#> 
#> ── Population Parameters ($parFixed or $parFixedDf): ──────────────────────
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
#>           Est.       SE    %RSE Back-transformed(95%CI) BSV(CV%)
#> tV0      -3.14 3.72e-05 0.00118 0.0432 (0.0432, 0.0432)    1210.
#> tkgrow   -3.64 8.68e-05 0.00239 0.0263 (0.0263, 0.0263)     168.
#> prop.err 0.368                                    0.368         
#>          Shrink(SD)%
#> tV0          -22.0% 
#> tkgrow        26.9% 
#> prop.err             
#> 
#>   Covariance Type ($covMethod): s
#>   No correlations in between subject variability (BSV) matrix
#>   Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
#>   Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
#>   Minimization message ($message):  
#>     false convergence (8) 
#>   In an ODE system, false convergence may mean "useless" evaluations were performed.
#>   See https://tinyurl.com/yyrrwkce
#>   It could also mean the convergence is poor, check results before accepting fit
#>   You may also try a good derivative free optimization:
#>     nlmixr(...,control=list(outerOpt="bobyqa"))
#> 
#> ── Fit Data (object is a modified tibble): ──────────────────────────────── 
#> # A tibble: 2,500 x 18
#>      ID  TIME     DV  EVID   PRED      RES     WRES  IPRED     IRES  IWRES
#>   <int> <dbl>  <dbl> <int>  <dbl>    <dbl>    <dbl>  <dbl>    <dbl>  <dbl>
#> 1     1     2 0          0 0.0456 -0.0456  -0.0147  0.0260 -0.0260  -2.72 
#> 2     1     9 0.0469     0 0.0548 -0.00790 -0.00255 0.0409  0.00595  0.395
#> 3     1    16 0.0765     0 0.0658  0.0107   0.00344 0.0644  0.0121   0.510
#> # … with 2,497 more rows, and 8 more variables: CPRED <dbl>, CRES <dbl>,
#> #   CWRES <dbl>, eta.V0 <dbl>, eta.kgrow <dbl>, V0 <dbl>, KGROW <dbl>,
#> #   V <dbl>
```

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DimitrisVoul** [comment]
Thank you that worked after updating the RxODE. I had the latest version and it was still crashing. I needed to do the manual update you recommended.

**Comment by mattfidler** [comment]
I think that RxODE and nlimixr are cross-linked so they have to compiled against each other.

I'm glad the manual install worked well.
