### ISSUE TITLE
How to deploy nlmixr-based shiny app to server?

### ISSUE THREAD

**Issue by leojanetguo** [nlmixrdevelopment/nlmixr#470]
Hello,

I am curious if it is possible to deploy nlmixr-based shiny app to servers like Shinyapps.io? And how?

I have built a model with nlmixr and embedded it into a shiny dashboard to interactively visualize the estimation output. Everything runs perfectly locally, but on the Shiny server, it fails. I tried the method described in the link [here](https://github.com/ranikay/shiny-reticulate-app) (used the same `.Rprofile` and only changed `PYTHON_DEPENDENCIES = c('sympy')`), but it still doesn't work.

Any ideas or suggestions would be much appreciated!

**Comment by mattfidler** [comment]
What are you trying to do? That would affect the advice.  Simulation? Estimation?

**Comment by mattfidler** [comment]
Also what sort of errors are you getting?

**Comment by leojanetguo** [comment]
Sorry, I should make it straightforward. I am trying to do the estimation. The nlmixr+shiny app allows me to input the PK data, run the estimation, and show the estimated PK parameters I need in the output. I am looking for a way to deploy the app to the server so that someone without R installation can access it from the web. Here is a basic example that mimics what I am trying to do. 

**global.R**
```
library(nlmixr)
library(shiny)
one.compartment <- function() {
  ini({
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    tv <- 3.45    # Log V
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}
```
**ui.R**
```
fixedPage(
  hr(),
  sidebarLayout(
    sidebarPanel(
      actionButton("estimate", "Begin estimation", class = "btn-success")
    ),
    
    mainPanel(
      dataTableOutput("mytable")
    )
  )
)
```
**server.R**
```
shinyServer(function(input, output, session) {
  
  PK <- eventReactive(input$estimate, {
    
    withProgress(
      message = "Estimating",
      value = 0, {
        fit <- nlmixr(one.compartment, theo_sd, list(print=0), est="saem")
        fit <- as.data.frame(fit)
      })
  })
  
  output$mytable <- renderDataTable({
    PK()
  })
  
  session$onSessionEnded(function() {
    stopApp()	#Stops the R session when Google Chrome/R Studio window closes
  })	#Brackets closing "session"
})	#Brackets closing "shinyServer"

```
It runs perfectly locally. When I deploy it to shinyapps.io, I change the `server.R` and `.Rprofile` a little bit using the method described [here](https://github.com/ranikay/shiny-reticulate-app). 

**server.R**
```
PYTHON_DEPENDENCIES = c('sympy')

shinyServer(function(input, output, session) {

  virtualenv_dir = Sys.getenv('VIRTUALENV_NAME')
  python_path = Sys.getenv('PYTHON_PATH')
  
  # Create virtual env and install dependencies
  reticulate::virtualenv_create(envname = virtualenv_dir, python = python_path)
  reticulate::virtualenv_install(virtualenv_dir, packages = PYTHON_DEPENDENCIES, ignore_installed=TRUE)
  reticulate::use_virtualenv(virtualenv_dir, required = T)
  
  PK <- eventReactive(input$estimate, {
    
    withProgress(
      message = "Estimating",
      value = 0, {
        fit <- nlmixr(one.compartment, theo_sd, list(print=0), est="saem")
        fit <- as.data.frame(fit)
      })
  })
  
  output$mytable <- renderDataTable({
    PK()
  })
  
  session$onSessionEnded(function() {
    stopApp()	#Stops the R session when Google Chrome/R Studio window closes
  })	#Brackets closing "session"
})	#Brackets closing "shinyServer"

```

**.Rprofile**
```
# This file configures the virtualenv and Python paths differently depending on
# the environment the app is running in (local vs remote server).

# Edit this name if desired when starting a new app
VIRTUALENV_NAME = 'example_env_name'

# ------------------------- Settings (Do not edit) -------------------------- #

if (Sys.info()[['user']] == 'shiny'){
  
  # Running on shinyapps.io
  Sys.setenv(PYTHON_PATH = 'python3')
  Sys.setenv(VIRTUALENV_NAME = VIRTUALENV_NAME) # Installs into default shiny virtualenvs dir
  Sys.setenv(RETICULATE_PYTHON = paste0('/home/shiny/.virtualenvs/', VIRTUALENV_NAME, '/bin/python'))
  
} else if (Sys.info()[['user']] == 'rstudio-connect'){
  
  # Running on remote server
  Sys.setenv(PYTHON_PATH = '/opt/python/3.7.6/bin/python')
  Sys.setenv(VIRTUALENV_NAME = paste0(VIRTUALENV_NAME, '/')) # include '/' => installs into rstudio-connect/apps/
  Sys.setenv(RETICULATE_PYTHON = paste0(VIRTUALENV_NAME, '/bin/python'))
  
} else {
  
  # Running locally
  options(shiny.port = 7450)
  Sys.setenv(PYTHON_PATH = 'python3')
  Sys.setenv(VIRTUALENV_NAME = VIRTUALENV_NAME) # exclude '/' => installs into ~/.virtualenvs/
  # RETICULATE_PYTHON is not required locally, RStudio infers it based on the ~/.virtualenvs path
}
```
I deployed it to shinyapps.io and tried to run the app from the server, but it disconnected from the server after I click the "Begin estimation" button. Here is the log:

```
2021-01-20T18:23:14.042265+00:00 shinyapps[3497138]:       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
2021-01-20T18:23:14.042190+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/tests/test_calculus.py to test_calculus.cpython-35.pyc
2021-01-20T18:23:14.042192+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/tests/test_basic_ops.py to test_basic_ops.cpython-35.pyc
2021-01-20T18:23:14.042198+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/libmp/gammazeta.py to gammazeta.cpython-35.pyc
2021-01-20T18:23:14.042208+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/functions/rszeta.py to rszeta.cpython-35.pyc
2021-01-20T18:23:14.042229+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/ctx_mp.py to ctx_mp.cpython-35.pyc
2021-01-20T18:23:14.042247+00:00 shinyapps[3497138]:     Traceback (most recent call last):
2021-01-20T18:23:14.042266+00:00 shinyapps[3497138]:       File "/home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
2021-01-20T18:23:14.042192+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/tests/runtests.py to runtests.cpython-35.pyc
2021-01-20T18:23:14.042198+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/libmp/libintmath.py to libintmath.cpython-35.pyc
2021-01-20T18:23:14.042208+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/functions/orthogonal.py to orthogonal.cpython-35.pyc
2021-01-20T18:23:14.042229+00:00 shinyapps[3497138]:     running install_egg_info
2021-01-20T18:23:14.042247+00:00 shinyapps[3497138]:       File "<string>", line 1, in <module>
2021-01-20T18:23:14.042266+00:00 shinyapps[3497138]:         return orig.install.run(self)
2021-01-20T18:23:14.042196+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/tests/test_pickle.py to test_pickle.cpython-35.pyc
2021-01-20T18:23:14.042198+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/libmp/libmpc.py to libmpc.cpython-35.pyc
2021-01-20T18:23:14.042223+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/functions/factorials.py to factorials.cpython-35.pyc
2021-01-20T18:23:14.042229+00:00 shinyapps[3497138]:     running egg_info
2021-01-20T18:23:14.042248+00:00 shinyapps[3497138]:       File "/tmp/pip-install-abi8jzkb/mpmath_67f945f34a1f4a6eb2692aeb49a78347/setup.py", line 18, in <module>
2021-01-20T18:23:14.042267+00:00 shinyapps[3497138]:       File "/usr/lib/python3.5/distutils/command/install.py", line 595, in run
2021-01-20T18:23:14.042227+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/functions/elliptic.py to elliptic.cpython-35.pyc
2021-01-20T18:23:14.042230+00:00 shinyapps[3497138]:     writing top-level names to mpmath.egg-info/top_level.txt
2021-01-20T18:23:14.042248+00:00 shinyapps[3497138]:       File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
2021-01-20T18:23:14.042267+00:00 shinyapps[3497138]:       File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
2021-01-20T18:23:14.042228+00:00 shinyapps[3497138]:     byte-compiling /home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/mpmath/functions/theta.py to theta.cpython-35.pyc
2021-01-20T18:23:14.042231+00:00 shinyapps[3497138]:     reading manifest file 'mpmath.egg-info/SOURCES.txt'
2021-01-20T18:23:14.042265+00:00 shinyapps[3497138]:       File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
2021-01-20T18:23:14.042268+00:00 shinyapps[3497138]:       File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
2021-01-20T18:23:14.042230+00:00 shinyapps[3497138]:     writing dependency_links to mpmath.egg-info/dependency_links.txt
2021-01-20T18:23:14.042248+00:00 shinyapps[3497138]:         classifiers=['Topic :: Scientific/Engineering :: Mathematics']
2021-01-20T18:23:14.042267+00:00 shinyapps[3497138]:         self.run_command(cmd_name)
2021-01-20T18:23:14.042270+00:00 shinyapps[3497138]:     SyntaxError: invalid syntax
2021-01-20T18:23:14.042230+00:00 shinyapps[3497138]:     writing mpmath.egg-info/PKG-INFO
2021-01-20T18:23:14.042264+00:00 shinyapps[3497138]:         dist.run_commands()
2021-01-20T18:23:14.042267+00:00 shinyapps[3497138]:         self.distribution.run_command(command)
2021-01-20T18:23:14.042576+00:00 shinyapps[3497138]: ERROR: Command errored out with exit status 1: /home/shiny/.virtualenvs/example_env_name/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-abi8jzkb/mpmath_67f945f34a1f4a6eb2692aeb49a78347/setup.py'"'"'; __file__='"'"'/tmp/pip-install-abi8jzkb/mpmath_67f945f34a1f4a6eb2692aeb49a78347/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-00lzf7tb/install-record.txt --single-version-externally-managed --compile --install-headers /home/shiny/.virtualenvs/example_env_name/include/site/python3.5/mpmath Check the logs for full command output.
2021-01-20T18:23:14.042265+00:00 shinyapps[3497138]:         self.run_command(cmd)
2021-01-20T18:23:14.042268+00:00 shinyapps[3497138]:         cmd_obj.run()
2021-01-20T18:23:14.109079+00:00 shinyapps[3497138]:   62: stop
2021-01-20T18:23:14.042265+00:00 shinyapps[3497138]:         cmd_obj.run()
2021-01-20T18:23:14.042269+00:00 shinyapps[3497138]:         import setuptools.command.easy_install as ei
2021-01-20T18:23:14.109081+00:00 shinyapps[3497138]:   60: reticulate::virtualenv_install
2021-01-20T18:23:14.042269+00:00 shinyapps[3497138]:       File "/home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 719
2021-01-20T18:23:14.109082+00:00 shinyapps[3497138]:   59: server [/srv/connect/apps/example/server.R#11]
2021-01-20T18:23:14.042269+00:00 shinyapps[3497138]:         ):
2021-01-20T18:23:14.109202+00:00 shinyapps[3497138]: Error : Error installing package(s): 'sympy'
2021-01-20T18:23:14.042270+00:00 shinyapps[3497138]:         ^
2021-01-20T18:23:14.042270+00:00 shinyapps[3497138]:     ----------------------------------------
2021-01-20T18:23:14.103651+00:00 shinyapps[3497138]: Warning: Error in : Error installing package(s): 'sympy'
2021-01-20T18:23:14.042269+00:00 shinyapps[3497138]:       File "/home/shiny/.virtualenvs/example_env_name/lib/python3.5/site-packages/setuptools/command/install_scripts.py", line 17, in run
2021-01-20T18:23:14.109080+00:00 shinyapps[3497138]:   61: pip_install
```
It looks like the error comes from installing "sympy", but I don't know how to fix it.

**Comment by mattfidler** [comment]
You could try the development `RxODE` and `nlmixr`;  We no longer use python so the error would go away (but may have other errors, I have heard that shinyapps.io doesn't like `symengine`, though I'm unsure what to do about it either)

**Comment by mattfidler** [comment]
I opened an issue here: https://github.com/symengine/symengine.R/issues/105

**Comment by leojanetguo** [comment]
Just for an update. I turned to AWS cloud for deployment these days and it worked! Will try the development RxODE and nlmixr version in the future to see how that go. Thanks for letting me know about the symengine issue!

**Comment by mattfidler** [comment]
Thanks;  Hopefully they get cmake for `shinyapps.io`
