### ISSUE TITLE
Error installing SnakeCharmR

### ISSUE THREAD

**Issue by ortizem** [nlmixrdevelopment/nlmixr#52]
Hi,

I am trying to install SnakeCharmR in a RedHat Linux environment. 

Command used: install_github("nlmixrdevelopment/SnakeCharmR

Error Log:
```
* installing *source* package ‘SnakeCharmR’ ...
** package ‘SnakeCharmR’ successfully unpacked and MD5 sums checked
Using python-config...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
Found Python version ...
configure: creating ./config.status
config.status: creating src/Makevars
--------[begin src/Makevars]--------
# Required vars
PKG_LIBS=-lpthread -ldl -lutil -lm -lpython2.6
PKG_CPPFLAGS=-I/usr/include/python2.6 -I/usr/include/python2.6 -D PYTHONLIBFILE=\"libpython.so\"
CXX_STD = CXX11
--------[end src/Makevars]--------
** libs
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I/usr/include/python2.6 -I/usr/include/python2.6 -D PYTHONLIBFILE=\"libpython.so\" -I"/      usr/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protecto      r --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I/usr/include/python2.6 -I/usr/include/python2.6 -D PYTHONLIBFILE=\"libpython.so\" -I"/      usr/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protecto      r --param=ssp-buffer-size=4 -m64 -mtune=generic -c python.cpp -o python.o
In file included from /usr/include/python2.6/pyconfig.h:6:0,
                 from /usr/include/python2.6/Python.h:8,
                 from python.cpp:4:
/usr/include/python2.6/pyconfig-64.h:1034:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/x86_64-redhat-linux/bits/os_defines.h:39:0,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/x86_64-redhat-linux/bits/c++config.h:2255,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/cmath:41,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/r/headers.h:48,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:38,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
/usr/include/features.h:162:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 ^
In file included from /usr/include/python2.6/pyconfig.h:6:0,
                 from /usr/include/python2.6/Python.h:8,
                 from python.cpp:4:
/usr/include/python2.6/pyconfig-64.h:1043:0: warning: "_XOPEN_SOURCE" redefined
 #define _XOPEN_SOURCE 600
 ^
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/x86_64-redhat-linux/bits/os_defines.h:39:0,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/x86_64-redhat-linux/bits/c++config.h:2255,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/cmath:41,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/r/headers.h:48,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:38,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
/usr/include/features.h:164:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
 ^
g++ -m64 -std=gnu++0x -shared -L/usr/lib64/R/lib -o SnakeCharmR.so RcppExports.o python.o -lpthread -ldl -lutil -lm -lpython2.6 -L/usr/l      ib64/R/lib -lR
installing to /usr/lib64/R/library/SnakeCharmR/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘SnakeCharmR’
    finding HTML links ... done
    SnakeCharmR                             html
    py.assign                               html
    py.call                                 html
    py.exec                                 html
    py.get                                  html
    py.load                                 html
    py.rm                                   html
** building package indices
** testing if installed package can be loaded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.6/json/__init__.py", line 109, in <module>
    from .encoder import JSONEncoder
  File "/usr/lib64/python2.6/json/encoder.py", line 5, in <module>
    import math
ImportError: /usr/lib64/python2.6/lib-dynload/mathmodule.so: undefined symbol: PyExc_ValueError
Error: package or namespace load failed for ‘SnakeCharmR’:
 .onAttach failed in attachNamespace() for 'SnakeCharmR', details:
  call: py.get("sys.version")
  error: Traceback (most recent call last):
  File "<string>", line 3, in <module>
NameError: name 'json' is not defined

Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/lib64/R/library/SnakeCharmR’

The downloaded source packages are in
        ‘/tmp/RtmpKKpNmy/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("SnakeCharmR") :
  installation of package ‘SnakeCharmR’ had non-zero exit status
```

**Comment by mattfidler** [comment]
I think the installation instructions are at

https://github.com/asieira/SnakeCharmR

**Comment by mattfidler** [comment]
You could try adjusting `SNAKECHARMR_PYTHON_VERSION`

**Comment by mattfidler** [comment]
If you still have issues let us know.
